export const TEST_IDS = {
  flights: {
    results: 'flight-results',
    error: 'flights-error',
    empty: 'flights-empty',
    item: 'flight-result-item',
    book: 'book-flight',
  },
  search: {
    form: 'flight-search-form',
    origin: 'search-origin',
    destination: 'search-destination',
    date: 'search-date',
    passengers: 'search-passengers',
    submit: 'search-submit',
  },
  booking: {
    form: 'booking-form',
    flight: 'booking-flight',
    contactEmail: 'contact-email',
    contactPhone: 'contact-phone',
    addPassenger: 'add-passenger',
    submit: 'booking-submit',
    success: 'booking-success',
    code: 'booking-code',
    error: 'booking-error',
    flightNotFound: 'flight-not-found',
  },
  smoke: 'main-heading',
} as const;
