export const TEST_IDS = {
  flights: {
    results: 'flight-results',
    error: 'flights-error',
    empty: 'flights-empty',
    item: 'flight-result-item',
    book: 'book-flight',
  },
  search: {
    form: 'flight-search-form',
    origin: 'search-origin',
    destination: 'search-destination',
    date: 'search-date',
    passengers: 'search-passengers',
    submit: 'search-submit',
  },
  booking: {
    form: 'booking-form',
    flight: 'booking-flight',
    contactEmail: 'contact-email',
    contactPhone: 'contact-phone',
    addPassenger: 'add-passenger',
    submit: 'booking-submit',
    success: 'booking-success',
    code: 'booking-code',
    error: 'booking-error',
    flightNotFound: 'flight-not-found',
    passenger: (index: number) => ({
      firstName: `passenger-${index}-firstName`,
      lastName: `passenger-${index}-lastName`,
      dob: `passenger-${index}-dob`,
      document: `passenger-${index}-document`,
    }),
  },
  nav: {
    lookup: 'nav-lookup',
  },
  bookingLookup: {
    form: 'booking-lookup-form',
    mainCode: 'lookup-code',
    lastName: 'lookup-lastName',
    submit: 'lookup-submit',
    details: 'booking-details',
    code: 'booking-code',
    status: 'booking-status',
    cancel: 'cancel-booking',
    notFound: 'booking-not-found',
  },
  smoke: 'main-heading',
} as const;
